services:
  - type: web
    name: employee-management-system
    env: python
    plan: free
    rootDir: office_emp_proj            # <—— this is the sub-folder with manage.py
    buildCommand: |
      pip install -r ../requirements.txt
      python manage.py migrate --no-input
      python manage.py collectstatic --no-input
    startCommand: gunicorn office_emp_proj.office_emp_proj.wsgi:application --bind 0.0.0.0:$PORT

    autoDeploy: true